Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -70,10 +70,12 @@ runs:
       id: set-version
       run: |
         if [[ "${{ steps.ref.outputs.master }}" == "true" ]]; then
-            VERSION=$(mvn ${{inputs.maven_flag}} --non-recursive -q \
+             (mvn ${{inputs.maven_flag}} --non-recursive -q \
               build-helper:parse-version  exec:exec \
               -Dexec.executable=echo \
-              -Dexec.args='${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion}.0')
+              -Dexec.args='${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion}.0'\
+              || echo "Maven command failed!"
+              
         elif [[ "${{ steps.ref.outputs.hotfix }}" == "true" ]]; then 
             QUALIFIER=$(mvn ${{inputs.maven_flag}} --non-recursive -q \
               build-helper:parse-version  exec:exec \
@@ -87,10 +89,14 @@ runs:
               mvn ${{inputs.maven_flag}} -q scm:checkin -Dmessage="[ci skip] set snapshot version"
             fi
             VERSION=$(mvn ${{inputs.maven_flag}} help:evaluate -Dexpression=project.version -q -DforceStdout|sed 's/-SNAPSHOT//')
+            echo "Computed VERSION: $VERSION"
         else
             VERSION="dev-${GITHUB_SHA::8}"
         fi
-
+        if [[ -z "$VERSION" ]]; then
+            echo "Not able to get the version. Check Maven output above."
+            exit 1
+        fi
         if [[ "x$VERSION" = "x" ]]; then
             echo "Not able to get the version"
             exit 1
