Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -74,17 +74,17 @@ runs:
               build-helper:parse-version  exec:exec \
               -Dexec.executable=echo \
               -Dexec.args='${parsedVersion.majorVersion}.${parsedVersion.nextMinorVersion}.0') || {
-            		echo "Failed to generate version for master branch"
-            		exit 1
-        		}
+            	echo "Failed to generate version for master branch"
+            	exit 1
+        }
         elif [[ "${{ steps.ref.outputs.hotfix }}" == "true" ]]; then 
             QUALIFIER=$(mvn ${{inputs.maven_flag}} --non-recursive -q \
               build-helper:parse-version  exec:exec \
               -Dexec.executable=echo \
               -Dexec.args='${parsedVersion.qualifier}') || {
-        		    echo "Failed to extract qualifier for hotfix branch"
-        		    exit 1
-    		    }
+							echo "Failed to extract qualifier for hotfix branch"
+							exit 1
+						}
             if [[ -z "$QUALIFIER" ]]; then
               mvn ${{inputs.maven_flag}} -q build-helper:parse-version \
                 versions:set \
@@ -93,9 +93,9 @@ runs:
               mvn ${{inputs.maven_flag}} -q scm:checkin -Dmessage="[ci skip] set snapshot version"
             fi
             VERSION=$(mvn ${{inputs.maven_flag}} help:evaluate -Dexpression=project.version -q -DforceStdout|sed 's/-SNAPSHOT//') || {
-              echo "Failed to evaluate project version for hotfix branch"
-            	exit 1
-        		}
+							echo "Failed to evaluate project version for hotfix branch"
+			 				exit 1
+						}
         else
             VERSION="dev-${GITHUB_SHA::8}"
         fi
